version: 2.1
jobs:
    run_tests:
        docker:
            - image: cimg/node:18.16.0
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install --save
            - run:
                name: Run tests
                command: npm test
    build_docker:
        docker:
            - image: cimg/node:18.16.0
        steps:
            - checkout
            - run:
                name: Build Docker Image
                command: |
                    export TAG=0.2.<<pipeline.number>>
                    docker build -t amodh-2002/clone_website:$TAG .
                    docker tag amodh-2002/clone_website:$TAG amodh-2002/clone_website:latest
            - run:
                name: Push Docker Image
                command: |
                    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                    docker push amodh-2002/clone_website:$TAG
                    docker push amodh-2002/clone_website:latest

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - run_tests
            - build_docker
