apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-deployment
  labels:
    app: vite-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-react
  template:
    metadata:
      labels:
        app: vite-react
    spec:
      containers:
      - name: vite-react
        image: howaboutwepullsomeimages/fretboard:latest
        ports:
        - containerPort: 3000
