apiVersion: v1
kind: Service
metadata:
  name: vite-react-service
spec:
  type: NodePort
  selector:
    app: vite-react
  ports:
  - port: 3000
    nodePort: 31001  # any port within the range (30000-32767)
